### ISSUE TITLE
Problem Running ./build.sh

### ISSUE THREAD

**Issue by professor-nimrod** [tetrabiodistributed/tetra#52] opened 2020-08-13 21:10 UTC
Running `./build.sh` & `./serve.sh` may occasionally generate the following error:

`unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/professor_nimrod/Desktop/tetra_repos/project-tetra-docs/Dockerfile: no such file or directory`

Stackoverflow reports that this often occurs due to the files not being in the working directory, despite this being the case here. Strangely, the commands worked after manually pasting their contents into the CLI.

Error occurred on Ubuntu 20.04 LTS, in case its relevant

**Comment by capsulecorplab** [comment] 2020-08-13 23:17
Is this issue also happening on the `dev` branch?

**Comment by capsulecorplab** [comment] 2020-08-14 06:20
So, I was able to recreate the issue. The problem is in https://github.com/tetrabiodistributed/project-tetra-docs/blob/dev/build.sh#L4 where it's trying to build a docker image from a Dockerfile that doesn't exist. We can just remove line 3-5, since we're no longer building the image from a Dockerfile as of https://github.com/tetrabiodistributed/project-tetra-docs/commit/1269af7c0693ee1df59ba1b43338ff4cc3454b75.

**Comment by capsulecorplab** [comment] 2020-08-14 20:00
Closed as per #53. Idk why the closing keyword didn't work

**Closed as completed by capsulecorplab** 2020-08-14 20:00 UTC
Labels: bug
